Traceback (most recent call last):
  File "/Users/madsbertelsen/opt/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/madsbertelsen/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/madsbertelsen/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/madsbertelsen/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/madsbertelsen/opt/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/madsbertelsen/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/madsbertelsen/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/madsbertelsen/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
ms.make_sub_plot(data, log=True)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-16-5b17676ac509>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mms[0m[0;34m.[0m[0mmake_sub_plot[0m[0;34m([0m[0mdata[0m[0;34m,[0m [0mlog[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/PaNOSC/McStasScript/github/McStasScript/mcstasscript/interface/plotter.py[0m in [0;36mmake_sub_plot[0;34m(data_list, **kwargs)[0m
[1;32m     45[0m     """
[1;32m     46[0m [0;34m[0m[0m
[0;32m---> 47[0;31m     [0mfigsize[0m[0;34m,[0m [0mdata_list[0m [0;34m=[0m [0m_handle_kwargs[0m[0;34m([0m[0mdata_list[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     48[0m [0;34m[0m[0m
[1;32m     49[0m     [0mnumber_of_plots[0m [0;34m=[0m [0mlen[0m[0;34m([0m[0mdata_list[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/PaNOSC/McStasScript/github/McStasScript/mcstasscript/helper/plot_helper.py[0m in [0;36m_handle_kwargs[0;34m(data_list, **kwargs)[0m
[1;32m    249[0m                 [0;32mfor[0m [0mdata[0m [0;32min[0m [0mdata_list[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    250[0m                     [0minput_kwarg[0m [0;34m=[0m [0;34m{[0m[0moption[0m[0;34m:[0m [0mgiven_option[0m[0;34m}[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 251[0;31m                     [0mdata[0m[0;34m.[0m[0mset_plot_options[0m[0;34m([0m[0;34m**[0m[0minput_kwarg[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    252[0m [0;34m[0m[0m
[1;32m    253[0m             [0;31m# Remove option from kwargs[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: 'NoneType' object has no attribute 'set_plot_options'
AttributeError: 'NoneType' object has no attribute 'set_plot_options'

